In [81]:
import datetime
from strenum import StrEnum
import requests
import pandas as pd

In [82]:
class URL(StrEnum):
    TWSE_CLOSING_PRICE = (
        "https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_AVG_ALL"
    )
    TPEX_CLOSEING_PRICE = (
        "https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes"
    )

In [59]:
res = requests.get(url=URL.TPEX_CLOSEING_PRICE)
df = pd.DataFrame(res.json())
df_ = df[['Code','Name','ClosingPrice']]
df_.columns = ['code','name','close']
df_[df_['code']=='6417']

Empty DataFrame
Columns: [code, name, close]
Index: []

In [83]:
res = requests.get(url=URL.TPEX_CLOSEING_PRICE)
df = pd.DataFrame(res.json())

In [84]:
res = requests.get(url=URL.TPEX_CLOSEING_PRICE)
res.json()[0]

{'Date': '1120425',
 'SecuritiesCompanyCode': '006201',
 'CompanyName': '元大富櫃50',
 'Close': '17.36',
 'Change': '-0.53 ',
 'Open': '17.80',
 'High': '17.81',
 'Low': '17.25',
 'Average': '17.44',
 'TradingShares': '100088',
 'TransactionAmount': '1745092',
 'TransactionNumber': '132',
 'LatestBidPrice': '17.36',
 'LatesAskPrice': '17.37',
 'Capitals': '19446000',
 'NextReferencePrice': '17.36',
 'NextLimitUp': '19.09',
 'NextLimitDown': '15.63'}

In [87]:
tpex = { item['SecuritiesCompanyCode']: {'name':item['CompanyName'],'close':item['Close']} for item in res.json()}
tpex

{'006201': {'name': '元大富櫃50', 'close': '17.36'},
 '00679B': {'name': '元大美債20年', 'close': '32.50'},
 '00687B': {'name': '國泰20年美債', 'close': '33.61'},
 '00694B': {'name': '富邦美債1-3', 'close': '38.73'},
 '00695B': {'name': '富邦美債7-10', 'close': '35.10'},
 '00696B': {'name': '富邦美債20年', 'close': '34.07'},
 '00697B': {'name': '元大美債7-10', 'close': '36.35'},
 '00718B': {'name': '富邦中國政策債', 'close': '20.09'},
 '00719B': {'name': '元大美債1-3', 'close': '30.59'},
 '00720B': {'name': '元大投資級公司債', 'close': '34.71'},
 '00721B': {'name': '元大中國債3-5', 'close': '45.57'},
 '00722B': {'name': '群益15年IG電信債', 'close': '37.84'},
 '00723B': {'name': '群益15年IG科技債', 'close': '33.90'},
 '00724B': {'name': '群益10年IG金融債', 'close': '33.44'},
 '00725B': {'name': '國泰投資級公司債', 'close': '36.50'},
 '00726B': {'name': '國泰5Y+新興債', 'close': '33.50'},
 '00727B': {'name': '國泰1-5Y非投等債', 'close': '37.10'},
 '00734B': {'name': '台新JPM新興債', 'close': '15.63'},
 '00740B': {'name': '富邦全球投等債', 'close': '39.16'},
 '00741B': {'name': '富邦全球非投等債', 'close': '35.81'},
 '00744B': {'name': '國泰中國政金債5+', 'close': '43.36'},
 '00746B': {'name': '富邦A級公司債', 'close': '36.77'},
 '00749B': {'name': '凱基新興債10+', 'close': '31.72'},
 '00750B': {'name': '凱基科技債10+', 'close': '34.91'},
 '00751B': {'name': '元大AAA至A公司債', 'close': '35.45'},
 '00754B': {'name': '群益AAA-AA公司債', 'close': '37.73'},
 '00755B': {'name': '群益15年IG公用債', 'close': '35.20'},
 '00756B': {'name': '群益15年EM主權債', 'close': '32.98'},
 '00758B': {'name': '復華能源債', 'close': '52.45'},
 '00759B': {'name': '復華製藥債', 'close': '57.80'},
 '00760B': {'name': '復華新興企業債', 'close': '53.20'},
 '00761B': {'name': '國泰A級公司債', 'close': '37.36'},
 '00764B': {'name': '群益25年美債', 'close': '33.89'},
 '00765B': {'name': '群益中國政金債', 'close': '39.42'},
 '00768B': {'name': '復華20年美債', 'close': '57.10'},
 '00772B': {'name': '中信高評級公司債', 'close': '36.01'},
 '00773B': {'name': '中信優先金融債', 'close': '36.00'},
 '00777B': {'name': '凱基AAA至A公司債', 'close': '35.75'},
 '00778B': {'name': '凱基金融債20+', 'close': '35.53'},
 '00779B': {'name': '凱基美債25+', 'close': '33.94'},
 '00780B': {'name': '國泰A級金融債', 'close': '36.02'},
 '00781B': {'name': '國泰A級科技債', 'close': '33.59'},
 '00782B': {'name': '國泰A級公用債', 'close': '33.35'},
 '00784B': {'name': '富邦中國投等債', 'close': '36.18'},
 '00785B': {'name': '富邦金融投等債', 'close': '34.55'},
 '00786B': {'name': '元大10年IG銀行債', 'close': '33.56'},
 '00787B': {'name': '元大10年IG醫療債', 'close': '35.21'},
 '00788B': {'name': '元大10年IG電能債', 'close': '32.32'},
 '00789B': {'name': '復華公司債A3', 'close': '53.60'},
 '00790B': {'name': '復華次順位金融債', 'close': '53.00'},
 '00791B': {'name': '復華信用債1-5', 'close': '53.15'},
 '00792B': {'name': '群益A級公司債', 'close': '34.10'},
 '00793B': {'name': '群益AAA-A醫療債', 'close': '33.99'},
 '00794B': {'name': '群益7+中國政金債', 'close': '40.24'},
 '00795B': {'name': '中信美國公債20年', 'close': '32.92'},
 '00799B': {'name': '國泰A級醫療債', 'close': '34.00'},
 '00831B': {'name': '新光美債1-3', 'close': '37.70'},
 '00834B': {'name': '第一金金融債10+', 'close': '33.83'},
 '00836B': {'name': '永豐10年A公司債', 'close': '31.26'},
 '00840B': {'name': '凱基IG精選15+', 'close': '32.47'},
 '00841B': {'name': '凱基AAA-AA公司債', 'close': '32.54'},
 '00842B': {'name': '台新美元銀行債', 'close': '32.40'},
 '00844B': {'name': '新光15年IG金融債', 'close': '32.30'},
 '00845B': {'name': '富邦新興投等債', 'close': '31.62'},
 '00846B': {'name': '富邦歐洲銀行債', 'close': '33.32'},
 '00847B': {'name': '中信美國市政債', 'close': '28.26'},
 '00848B': {'name': '中信新興亞洲債', 'close': '33.76'},
 '00849B': {'name': '中信EM主權債0-5', 'close': '35.52'},
 '00853B': {'name': '統一美債10年Aa-A', 'close': '29.64'},
 '00856B': {'name': '永豐1-3年美公債', 'close': '37.36'},
 '00857B': {'name': '永豐20年美公債', 'close': '28.23'},
 '00858': {'name': '永豐美國500大', 'close': '25.69'},
 '00859B': {'name': '群益0-1年美債', 'close': '39.34'},
 '00860B': {'name': '群益1-5年IG債', 'close': '37.17'},
 '00862B': {'name': '中信投資級公司債', 'close': '32.16'},
 '00863B': {'name': '中信全球電信債', 'close': '33.01'},
 '00864B': {'name': '中信美國公債0-1', 'close': '41.02'},
 '00867B': {'name': '新光A-BBB電信債', 'close': '32.37'},
 '00870B': {'name': '元大15年EM主權債', 'close': '29.74'},
 '00877': {'name': '復華中國5G', 'close': '10.80'},
 '00883B': {'name': '中信ESG投資級債', 'close': '31.81'},
 '00884B': {'name': '中信低碳新興債', 'close': '30.52'},
 '00886': {'name': '永豐美國科技', 'close': '20.10'},
 '00887': {'name': '永豐中國科技50大', 'close': '14.72'},
 '00888': {'name': '永豐台灣ESG', 'close': '13.07'},
 '00890B': {'name': '凱基ESG BBB債15+', 'close': '33.58'},
 '020001': {'name': '富邦存股雙十N', 'close': ' ---'},
 '02001B': {'name': '統一美國政府債N', 'close': '8.39'},
 '020023': {'name': '元大櫃買半導體N', 'close': '4.97'},
 '020024': {'name': '兆豐富櫃200N', 'close': ' ---'},
 '020025': {'name': '統一亞洲半導體N', 'close': '6.62'},
 '020026': {'name': '兆豐上櫃ESG電菁N', 'close': '4.25'},
 '020027': {'name': '元大上櫃ESG成長N', 'close': '4.21'},
 '02002L': {'name': '兆豐富櫃200正二N', 'close': '5.29'},
 '020033': {'name': '統一恒生科期N', 'close': '3.50'},
 '020035': {'name': '元大上櫃ESG高息N', 'close': '5.79'},
 '1240': {'name': '茂生農經', 'close': '45.00'},
 '1258': {'name': '其祥-KY', 'close': '26.80'},
 '1259': {'name': '安心', 'close': '72.60'},
 '1264': {'name': '德麥', 'close': '275.00'},
 '1268': {'name': '漢來美食', 'close': '146.00'},
 '1336': {'name': '台翰', 'close': '25.50'},
 '1565': {'name': '精華', 'close': '246.50'},
 '1569': {'name': '濱川', 'close': '23.55'},
 '1570': {'name': '力肯', 'close': '18.10'},
 '1580': {'name': '新麥', 'close': '102.00'},
 '1584': {'name': '精剛', 'close': '39.80'},
 '1586': {'name': '和勤', 'close': '33.50'},
 '1591': {'name': '駿吉-KY', 'close': '26.80'},
 '1593': {'name': '祺驊', 'close': '75.20'},
 '1595': {'name': '川寶', 'close': '38.75'},
 '1599': {'name': '宏佳騰', 'close': '37.95'},
 '1742': {'name': '台蠟', 'close': '14.70'},
 '1777': {'name': '生泰', 'close': '86.20'},
 '1781': {'name': '合世', 'close': '14.55'},
 '1784': {'name': '訊聯', 'close': '60.80'},
 '1785': {'name': '光洋科', 'close': '34.95'},
 '1788': {'name': '杏昌', 'close': '142.50'},
 '1796': {'name': '金穎生技', 'close': '122.00'},
 '1799': {'name': '易威', 'close': '19.45'},
 '1813': {'name': '寶利徠', 'close': '22.30'},
 '1815': {'name': '富喬', 'close': '11.70'},
 '2035': {'name': '唐榮', 'close': '31.20'},
 '2061': {'name': '風青', 'close': '19.35'},
 '2063': {'name': '世鎧', 'close': '40.10'},
 '2064': {'name': '晉椿', 'close': '17.15'},
 '2065': {'name': '世豐', 'close': '58.00'},
 '2066': {'name': '世德', 'close': '92.20'},
 '2067': {'name': '嘉鋼', 'close': '12.20'},
 '2070': {'name': '精湛', 'close': '32.20'},
 '2221': {'name': '大甲', 'close': '41.70'},
 '2230': {'name': '泰茂', 'close': '79.60'},
 '2235': {'name': '謚源', 'close': '45.35'},
 '2596': {'name': '綠意', 'close': '22.10'},
 '2640': {'name': '大車隊', 'close': '116.00'},
 '2641': {'name': '正德', 'close': '18.30'},
 '2643': {'name': '捷迅', 'close': '68.80'},
 '2718': {'name': '晶悅', 'close': ' ---'},
 '2719': {'name': '燦星旅', 'close': '41.40'},
 '2724': {'name': '富驛-KY', 'close': '13.00'},
 '2726': {'name': '雅茗-KY', 'close': '26.45'},
 '2729': {'name': '瓦城', 'close': '228.00'},
 '2732': {'name': '六角', 'close': '166.50'},
 '2734': {'name': '易飛網', 'close': '32.40'},
 '2736': {'name': '富野', 'close': '21.50'},
 '2740': {'name': '天蔥', 'close': '46.00'},
 '2743': {'name': '山富', 'close': '57.00'},
 '2745': {'name': '五福', 'close': '39.85'},
 '2752': {'name': '豆府', 'close': '245.00'},
 '2754': {'name': '亞洲藏壽司', 'close': '158.00'},
 '2755': {'name': '揚秦', 'close': '145.50'},
 '2756': {'name': '聯發國際', 'close': '144.00'},
 '2916': {'name': '滿心', 'close': '33.10'},
 '2924': {'name': '宏太-KY', 'close': '31.00'},
 '2926': {'name': '誠品生活', 'close': '65.20'},
 '2937': {'name': '集雅社', 'close': '34.15'},
 '2947': {'name': '振宇五金', 'close': '92.90'},
 '3064': {'name': '泰偉', 'close': ' ---'},
 '3066': {'name': '李洲', 'close': '23.65'},
 '3067': {'name': '全域', 'close': ' ---'},
 '3071': {'name': '協禧', 'close': '34.20'},
 '3078': {'name': '僑威', 'close': '52.00'},
 '3081': {'name': '聯亞', 'close': '116.50'},
 '3083': {'name': '網龍', 'close': '42.15'},
 '3085': {'name': '新零售', 'close': '21.40'},
 '3086': {'name': '華義', 'close': '69.10'},
 '3088': {'name': '艾訊', 'close': '74.60'},
 '3089': {'name': '億杰', 'close': '58.00'},
 '3093': {'name': '港建*', 'close': '37.30'},
 '3095': {'name': '及成', 'close': '23.80'},
 '3105': {'name': '穩懋', 'close': '165.00'},
 '3114': {'name': '好德', 'close': '26.70'},
 '3115': {'name': '富榮綱', 'close': ' ---'},
 '3118': {'name': '進階', 'close': '31.40'},
 '3122': {'name': '笙泉', 'close': '24.35'},
 '3128': {'name': '昇銳', 'close': '37.25'},
 '3131': {'name': '弘塑', 'close': '343.00'},
 '3141': {'name': '晶宏', 'close': '95.00'},
 '3147': {'name': '大綜', 'close': '65.50'},
 '3152': {'name': '璟德', 'close': '210.00'},
 '3162': {'name': '精確', 'close': '50.80'},
 '3163': {'name': '波若威', 'close': '51.90'},
 '3169': {'name': '亞信', 'close': '123.00'},
 '3171': {'name': '新洲', 'close': '17.35'},
 '3176': {'name': '基亞', 'close': '33.95'},
 '3178': {'name': '公準', 'close': '82.50'},
 '3188': {'name': '鑫龍騰', 'close': '13.80'},
 '3191': {'name': '和進', 'close': '8.15'},
 '3202': {'name': '樺晟', 'close': '17.40'},
 '3205': {'name': '佰研', 'close': '43.40'},
 '3206': {'name': '志豐', 'close': '32.55'},
 '3207': {'name': '耀勝', 'close': '73.50'},
 '3211': {'name': '順達', 'close': '75.20'},
 '3213': {'name': '茂訊', 'close': '50.40'},
 '3217': {'name': '優群', 'close': '100.00'},
 '3218': {'name': '大學光', 'close': '391.50'},
 '3219': {'name': '倚強科', 'close': ' ---'},
 '3221': {'name': '台嘉碩', 'close': '28.15'},
 '3224': {'name': '三顧', 'close': '55.50'},
 '3226': {'name': '至寶電', 'close': '58.40'},
 '3227': {'name': '原相', 'close': '101.50'},
 '3228': {'name': '金麗科', 'close': '159.00'},
 '3230': {'name': '錦明', 'close': '13.15'},
 '3232': {'name': '昱捷', 'close': '29.50'},
 '3234': {'name': '光環', 'close': '22.85'},
 '3236': {'name': '千如', 'close': '27.85'},
 '3252': {'name': '海灣', 'close': '17.75'},
 '3259': {'name': '鑫創', 'close': '19.20'},
 '3260': {'name': '威剛', 'close': '71.00'},
 '3264': {'name': '欣銓', 'close': '53.00'},
 '3265': {'name': '台星科', 'close': '52.50'},
 '3268': {'name': '海德威', 'close': '22.15'},
 '3272': {'name': '東碩', 'close': '42.45'},
 '3276': {'name': '宇環', 'close': '14.10'},
 '3284': {'name': '太普高', 'close': '15.85'},
 '3285': {'name': '微端', 'close': '19.95'},
 '3287': {'name': '廣寰科', 'close': '13.80'},
 '3288': {'name': '點晶', 'close': '22.00'},
 '3289': {'name': '宜特', 'close': '79.90'},
 '3290': {'name': '東浦', 'close': '26.70'},
 '3293': {'name': '鈊象', 'close': '518.00'},
 '3294': {'name': '英濟', 'close': '19.20'},
 '3297': {'name': '杭特', 'close': '17.50'},
 '3303': {'name': '岱稜', 'close': '27.25'},
 '3306': {'name': '鼎天', 'close': '25.00'},
 '3310': {'name': '佳穎', 'close': '67.50'},
 '3313': {'name': '斐成', 'close': '10.15'},
 '3317': {'name': '尼克森', 'close': '54.30'},
 '3322': {'name': '建舜電', 'close': '21.25'},
 '3323': {'name': '加百裕', 'close': '33.10'},
 '3324': {'name': '雙鴻', 'close': '226.50'},
 '3325': {'name': '旭品', 'close': '17.05'},
 '3332': {'name': '幸康', 'close': '49.05'},
 '3339': {'name': '泰谷', 'close': '12.85'},
 '3349': {'name': '寶德', 'close': '13.60'},
 '3354': {'name': '律勝', 'close': '13.95'},
 '3357': {'name': '臺慶科', 'close': '101.00'},
 '3360': {'name': '尚立', 'close': '13.70'},
 '3362': {'name': '先進光', 'close': '90.30'},
 '3363': {'name': '上詮', 'close': '29.20'},
 '3372': {'name': '典範', 'close': '11.90'},
 '3373': {'name': '熱映', 'close': '22.60'},
 '3374': {'name': '精材', 'close': '97.80'},
 '3379': {'name': '彬台', 'close': '12.25'},
 '3388': {'name': '崇越電', 'close': '74.20'},
 '3390': {'name': '旭軟', 'close': '17.85'},
 '3402': {'name': '漢科', 'close': '51.90'},
 '3426': {'name': '台興', 'close': '39.70'},
 '3430': {'name': '奇鈦科', 'close': '48.00'},
 '3434': {'name': '哲固', 'close': '28.15'},
 '3438': {'name': '類比科', 'close': '53.90'},
 '3441': {'name': '聯一光', 'close': '41.05'},
 '3444': {'name': '利機', 'close': '62.50'},
 '3455': {'name': '由田', 'close': '86.70'},
 '3465': {'name': '進泰電子', 'close': '90.30'},
 '3466': {'name': '致振', 'close': '33.20'},
 '3479': {'name': '安勤', 'close': '96.20'},
 '3483': {'name': '力致', 'close': '65.60'},
 '3484': {'name': '崧騰', 'close': '45.65'},
 '3489': {'name': '森寶', 'close': '11.05'},
 '3490': {'name': '單井', 'close': '26.40'},
 '3491': {'name': '昇達科', 'close': '161.50'},
 '3492': {'name': '長盛', 'close': '20.50'},
 '3498': {'name': '陽程', 'close': '32.15'},
 '3499': {'name': '環天科', 'close': '21.40'},
 '3508': {'name': '位速', 'close': '31.60'},
 '3511': {'name': '矽瑪', 'close': '33.40'},
 '3512': {'name': '皇龍', 'close': '32.55'},
 '3516': {'name': '亞帝歐', 'close': '17.70'},
 '3520': {'name': '華盈', 'close': '22.10'},
 '3521': {'name': '鴻翊', 'close': '23.80'},
 '3522': {'name': '御頂', 'close': '14.20'},
 '3523': {'name': '迎輝', 'close': '18.50'},
 '3526': {'name': '凡甲', 'close': '132.50'},
 '3527': {'name': '聚積', 'close': '112.00'},
 '3529': {'name': '力旺', 'close': '1815.00'},
 '3531': {'name': '先益', 'close': '27.50'},
 '3537': {'name': '堡達', 'close': '37.40'},
 '3540': {'name': '曜越', 'close': '38.90'},
 '3541': {'name': '西柏', 'close': '59.70'},
 '3546': {'name': '宇峻', 'close': '78.70'},
 '3548': {'name': '兆利', 'close': '69.40'},
 '3551': {'name': '世禾', 'close': '59.00'},
 '3552': {'name': '同致', 'close': '140.50'},
 '3555': {'name': '重鵬', 'close': '27.05'},
 '3556': {'name': '禾瑞亞', 'close': '64.00'},
 '3558': {'name': '神準', 'close': '276.50'},
 '3564': {'name': '其陽', 'close': '35.50'},
 '3567': {'name': '逸昌', 'close': '29.85'},
 '3570': {'name': '大塚', 'close': '137.00'},
 '3577': {'name': '泓格', 'close': '81.00'},
 '3580': {'name': '友威科', 'close': '55.50'},
 '3581': {'name': '博磊', 'close': '22.45'},
 '3587': {'name': '閎康', 'close': '185.50'},
 '3594': {'name': '磐儀', 'close': '51.60'},
 '3597': {'name': '映興', 'close': '25.35'},
 '3609': {'name': '三一東林', 'close': '42.30'},
 '3611': {'name': '鼎翰', 'close': '227.00'},
 '3615': {'name': '安可', 'close': '17.55'},
 '3623': {'name': '富晶通', 'close': '16.10'},
 '3624': {'name': '光頡', 'close': '71.70'},
 '3625': {'name': '西勝', 'close': '13.85'},
 '3628': {'name': '盈正', 'close': '48.65'},
 '3629': {'name': '地心引力', 'close': '86.50'},
 '3630': {'name': '新鉅科', 'close': '28.00'},
 '3631': {'name': '晟楠', 'close': '34.90'},
 '3632': {'name': '研勤', 'close': '14.00'},
 '3646': {'name': '艾恩特', 'close': '28.00'},
 '3663': {'name': '鑫科', 'close': '32.45'},
 '3664': {'name': '安瑞-KY', 'close': '27.00'},
 '3666': {'name': '光耀', 'close': '22.30'},
 '3672': {'name': '康聯訊', 'close': '28.90'},
 '3675': {'name': '德微', 'close': '302.00'},
 '3680': {'name': '家登', 'close': '331.50'},
 '3684': {'name': '榮昌', 'close': '63.00'},
 '3685': {'name': '元創精密', 'close': '20.65'},
 '3687': {'name': '歐買尬', 'close': '78.70'},
 '3689': {'name': '湧德', 'close': '37.15'},
 '3691': {'name': '碩禾', 'close': '106.00'},
 '3693': {'name': '營邦', 'close': '194.50'},
 '3707': {'name': '漢磊', 'close': '77.00'},
 '3709': {'name': '鑫聯大投控', 'close': '21.20'},
 '3710': {'name': '連展投控', 'close': '11.60'},
 '3713': {'name': '新晶投控', 'close': '27.20'},
 '4102': {'name': '永日', 'close': '32.05'},
 '4105': {'name': '東洋', 'close': '75.50'},
 '4107': {'name': '邦特', 'close': '112.00'},
 '4109': {'name': '加捷生醫', 'close': '16.90'},
 '4111': {'name': '濟生', 'close': '30.55'},
 '4113': {'name': '聯上', 'close': '16.10'},
 '4114': {'name': '健喬', 'close': '46.40'},
 '4116': {'name': '明基醫', 'close': '63.20'},
 '4120': {'name': '友華', 'close': '36.50'},
 '4121': {'name': '優盛', 'close': '27.50'},
 '4123': {'name': '晟德', 'close': '51.20'},
 '4126': {'name': '太醫', 'close': '84.00'},
 '4127': {'name': '天良', 'close': '15.20'},
 '4128': {'name': '中天', 'close': '61.50'},
 '4129': {'name': '聯合', 'close': '58.30'},
 '4129A': {'name': '聯合甲特', 'close': '58.00'},
 '4130': {'name': '健亞', 'close': '26.85'},
 '4131': {'name': '晶宇', 'close': '27.70'},
 '4138': {'name': '曜亞', 'close': '79.40'},
 '4139': {'name': '馬光-KY', 'close': '37.50'},
 '4147': {'name': '中裕', 'close': '112.00'},
 '4153': {'name': '鈺緯', 'close': '45.70'},
 '4154': {'name': '樂威科-KY', 'close': '31.65'},
 '4157': {'name': '太景*-KY', 'close': '15.10'},
 '4160': {'name': '創源', 'close': '35.40'},
 '4161': {'name': '聿新科', 'close': '29.25'},
 '4162': {'name': '智擎', 'close': '97.00'},
 '4163': {'name': '鐿鈦', 'close': '127.50'},
 '4167': {'name': '松瑞藥', 'close': '18.35'},
 '4168': {'name': '醣聯', 'close': '30.70'},
 '4171': {'name': '瑞基', 'close': '57.10'},
 '4173': {'name': '久裕', 'close': '19.30'},
 '4174': {'name': '浩鼎', 'close': '85.20'},
 '4175': {'name': '杏一', 'close': '107.50'},
 '4183': {'name': '福永生技', 'close': '19.25'},
 '4188': {'name': '安克', 'close': '15.90'},
 '4192': {'name': '杏國', 'close': '19.30'},
 '4198': {'name': '欣大健康', 'close': ' ---'},
 '4205': {'name': '中華食', 'close': '105.50'},
 '4207': {'name': '環泰', 'close': '14.95'},
 '4303': {'name': '信立', 'close': '16.90'},
 '4304': {'name': '勝昱', 'close': '9.99'},
 '4305': {'name': '世坤', 'close': '31.30'},
 '4401': {'name': '東隆興', 'close': '27.25'},
 '4402': {'name': '福大', 'close': '10.20'},
 '4406': {'name': '新昕纖', 'close': '10.15'},
 '4413': {'name': '飛寶企業', 'close': '14.90'},
 '4416': {'name': '三圓', 'close': ' ---'},
 '4417': {'name': '金洲', 'close': '40.15'},
 '4419': {'name': '元勝', 'close': ' ---'},
 '4420': {'name': '光明', 'close': '29.60'},
 '4430': {'name': '耀億', 'close': '22.85'},
 '4432': {'name': '銘旺實', 'close': '21.05'},
 '4433': {'name': '興采', 'close': '34.45'},
 '4502': {'name': '健信', 'close': '37.00'},
 '4503': {'name': '金雨', 'close': '54.00'},
 '4506': {'name': '崇友', 'close': '73.40'},
 '4510': {'name': '高鋒', 'close': '14.05'},
 '4513': {'name': '福裕', 'close': '20.15'},
 '4523': {'name': '永彰', 'close': '35.90'},
 '4527': {'name': '方土霖', 'close': '31.00'},
 '4528': {'name': '江興鍛', 'close': '32.35'},
 '4529': {'name': '淳紳', 'close': '10.05'},
 '4530': {'name': '宏易', 'close': '6.80'},
 '4533': {'name': '協易機', 'close': '11.50'},
 '4534': {'name': '慶騰', 'close': '9.66'},
 '4535': {'name': '至興', 'close': '39.50'},
 '4538': {'name': '大詠城', 'close': '20.85'},
 '4541': {'name': '晟田', 'close': '38.50'},
 '4542': {'name': '科嶠', 'close': '27.00'},
 '4543': {'name': '萬在', 'close': '26.20'},
 '4549': {'name': '桓達', 'close': '92.70'},
 '4550': {'name': '長佳', 'close': '31.25'},
 '4554': {'name': '橙的', 'close': '28.70'},
 '4556': {'name': '旭然', 'close': '31.10'},
 '4558': {'name': '寶緯', 'close': '27.90'},
 '4561': {'name': '健椿', 'close': '24.00'},
 '4563': {'name': '百德', 'close': '38.75'},
 '4568': {'name': '科際精密', 'close': '60.50'},
 '4577': {'name': '達航科技', 'close': '30.95'},
 '4580': {'name': '捷流閥業', 'close': '94.70'},
 '4584': {'name': '君帆', 'close': '49.50'},
 '4609': {'name': '唐鋒', 'close': '7.59'},
 '4702': {'name': '中美實', 'close': '13.45'},
 '4706': {'name': '大恭', 'close': '17.15'},
 '4707': {'name': '磐亞', 'close': '12.75'},
 '4711': {'name': '永純', 'close': '15.05'},
 '4712': {'name': '南璋', 'close': '4.42'},
 '4714': {'name': '永捷', 'close': '11.95'},
 '4716': {'name': '大立', 'close': '12.25'},
 '4721': {'name': '美琪瑪', 'close': '99.90'},
 '4726': {'name': '永昕', 'close': '37.90'},
 '4728': {'name': '雙美', 'close': '255.00'},
 '4729': {'name': '熒茂', 'close': '16.70'},
 '4735': {'name': '豪展', 'close': '38.00'},
 '4736': {'name': '泰博', 'close': '180.50'},
 '4741': {'name': '泓瀚', 'close': '38.70'},
 '4743': {'name': '合一', 'close': '242.00'},
 '4744': {'name': '皇將', 'close': '34.15'},
 '4745': {'name': '合富-KY', 'close': '27.00'},
 '4747': {'name': '強生', 'close': '54.70'},
 '4754': {'name': '國碳科', 'close': '40.05'},
 '4760': {'name': '勤凱', 'close': '65.90'},
 '4767': {'name': '誠泰科技', 'close': '28.95'},
 '4768': {'name': '晶呈科技', 'close': '168.00'},
 '4804': {'name': '大略-KY', 'close': '6.23'},
 '4903': {'name': '聯光通', 'close': '19.50'},
 '4905': {'name': '台聯電', 'close': '51.00'},
 '4907': {'name': '富宇', 'close': '34.50'},
 '4908': {'name': '前鼎', 'close': '33.75'},
 '4909': {'name': '新復興', 'close': '17.85'},
 '4911': {'name': '德英', 'close': '68.60'},
 '4923': {'name': '力士', 'close': '59.00'},
 '4924': {'name': '欣厚-KY', 'close': '13.00'},
 '4931': {'name': '新盛力', 'close': '45.05'},
 '4933': {'name': '友輝', 'close': '35.10'},
 '4939': {'name': '亞電', 'close': '16.20'},
 '4944': {'name': '兆遠', 'close': '12.45'},

In [77]:
twse = [{'code':item['Code'],'name':item['Name'],'close':item['ClosingPrice'] }for item in res.json()]

In [72]:
df = pd.DataFrame(res.json())
df_ = df[['Code','ClosingPrice']]
df_.columns = ['Code','Close']
for _,row in df_.iterrows():
    print(row.to_dict())
    break

{'Code': '0050', 'Close': '118.15'}

In [26]:
for k,v in res.headers.items():
    print(f"{k} : {v}")

Server : nginx
Date : Mon, 24 Apr 2023 07:55:49 GMT
Content-Type : application/json
Last-Modified : Sun, 23 Apr 2023 21:00:42 GMT
Transfer-Encoding : chunked
Connection : keep-alive
ETag : W/"64459c7a-1cbe11"
Content-Disposition : attachment;filename=STOCK_DAY_AVG_ALL.json
Content-Encoding : gzip

In [2]:
import requests
import datetime
import ujson as json
import adodbapi
import pandas as pd
            
password = r"St0ck%%Book"
cons_str = f"Provider=Microsoft.SQLSERVER.CE.OLEDB.3.5;Data Source=./data/StockBook.sdf;SSCE:Database Password={password};Mode=ReadWrite|Share Deny None;"
connection = adodbapi.connect(cons_str,)
cursor = connection.cursor()

In [54]:
cursor.execute("SELECT * FROM Stock")
sdf = cursor.fetchall()

In [57]:
exist_code = sdf.ado_results[0]

('0015',
 '0050',
 '0051',
 '0052',
 '0053',
 '0054',
 '0055',
 '0056',
 '0057',
 '0058',
 '0059',
 '0060',
 '0061',
 '0080',
 '0081',
 '01001T',
 '01002T',
 '01003T',
 '01004T',
 '01005T',
 '01007T',
 '01008T',
 '1101',
 '1102',
 '1103',
 '1104',
 '1108',
 '1109',
 '1110',
 '1201',
 '1203',
 '1210',
 '1213',
 '1215',
 '1216',
 '1217',
 '1218',
 '1219',
 '1220',
 '1225',
 '1227',
 '1229',
 '1231',
 '1232',
 '1233',
 '1234',
 '1235',
 '1236',
 '1301',
 '1303',
 '1304',
 '1305',
 '1307',
 '1308',
 '1309',
 '1310',
 '1312',
 '1313',
 '1314',
 '1315',
 '1316',
 '1319',
 '1321',
 '1323',
 '1324',
 '1325',
 '1326',
 '1402',
 '1409',
 '1410',
 '1413',
 '1414',
 '1416',
 '1417',
 '1418',
 '1419',
 '1423',
 '1432',
 '1434',
 '1435',
 '1436',
 '1437',
 '1438',
 '1439',
 '1440',
 '1441',
 '1442',
 '1443',
 '1444',
 '1445',
 '1446',
 '1447',
 '1449',
 '1451',
 '1452',
 '1453',
 '1454',
 '1455',
 '1456',
 '1457',
 '1459',
 '1460',
 '1463',
 '1464',
 '1465',
 '1466',
 '1467',
 '1468',
 '1469',
 '1470',
 '1471',
 '1472',
 '1473',
 '1474',
 '1475',
 '1476',
 '1477',
 '1503',
 '1504',
 '1506',
 '1507',
 '1512',
 '1513',
 '1514',
 '1515',
 '1516',
 '1517',
 '1519',
 '1521',
 '1522',
 '1523',
 '1524',
 '1525',
 '1526',
 '1527',
 '1528',
 '1529',
 '1530',
 '1531',
 '1532',
 '1533',
 '1535',
 '1536',
 '1537',
 '1538',
 '1539',
 '1540',
 '1541',
 '1560',
 '1582',
 '1583',
 '1603',
 '1604',
 '1605',
 '1608',
 '1609',
 '1611',
 '1612',
 '1613',
 '1614',
 '1615',
 '1616',
 '1617',
 '1618',
 '1701',
 '1702',
 '1704',
 '1707',
 '1708',
 '1709',
 '1710',
 '1711',
 '1712',
 '1713',
 '1714',
 '1715',
 '1716',
 '1717',
 '1718',
 '1720',
 '1721',
 '1722',
 '1723',
 '1724',
 '1725',
 '1726',
 '1727',
 '1729',
 '1730',
 '1731',
 '1732',
 '1733',
 '1734',
 '1735',
 '1736',
 '1737',
 '1773',
 '1802',
 '1805',
 '1806',
 '1808',
 '1809',
 '1810',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1909',
 '2002',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2012',
 '2013',
 '2014',
 '2015',
 '2017',
 '2020',
 '2022',
 '2023',
 '2024',
 '2025',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2038',
 '2049',
 '2059',
 '2062',
 '2101',
 '2102',
 '2103',
 '2104',
 '2105',
 '2106',
 '2107',
 '2108',
 '2109',
 '2201',
 '2204',
 '2206',
 '2207',
 '2208',
 '2227',
 '2301',
 '2302',
 '2303',
 '2305',
 '2308',
 '2311',
 '2312',
 '2313',
 '2314',
 '2315',
 '2316',
 '2317',
 '2321',
 '2323',
 '2324',
 '2325',
 '2327',
 '2328',
 '2329',
 '2330',
 '2331',
 '2332',
 '2337',
 '2338',
 '2340',
 '2341',
 '2342',
 '2344',
 '2345',
 '2347',
 '2348',
 '2349',
 '2350',
 '2351',
 '2352',
 '2353',
 '2354',
 '2355',
 '2356',
 '2358',
 '2359',
 '2360',
 '2361',
 '2362',
 '2363',
 '2364',
 '2365',
 '2367',
 '2368',
 '2369',
 '2371',
 '2373',
 '2374',
 '2375',
 '2376',
 '2377',
 '2379',
 '2380',
 '2382',
 '2383',
 '2384',
 '2385',
 '2387',
 '2388',
 '2390',
 '2391',
 '2392',
 '2393',
 '2395',
 '2397',
 '2399',
 '2401',
 '2402',
 '2403',
 '2404',
 '2405',
 '2406',
 '2408',
 '2409',
 '2412',
 '2413',
 '2414',
 '2415',
 '2417',
 '2419',
 '2420',
 '2421',
 '2423',
 '2424',
 '2425',
 '2426',
 '2427',
 '2428',
 '2429',
 '2430',
 '2431',
 '2433',
 '2434',
 '2436',
 '2437',
 '2438',
 '2439',
 '2440',
 '2441',
 '2442',
 '2443',
 '2444',
 '2448',
 '2449',
 '2450',
 '2451',
 '2453',
 '2454',
 '2455',
 '2456',
 '2457',
 '2458',
 '2459',
 '2460',
 '2461',
 '2462',
 '2463',
 '2464',
 '2465',
 '2466',
 '2467',
 '2468',
 '2471',
 '2472',
 '2473',
 '2474',
 '2475',
 '2476',
 '2477',
 '2478',
 '2480',
 '2481',
 '2482',
 '2483',
 '2484',
 '2485',
 '2486',
 '2488',
 '2489',
 '2491',
 '2492',
 '2493',
 '2495',
 '2496',
 '2497',
 '2498',
 '2499',
 '2501',
 '2504',
 '2505',
 '2506',
 '2509',
 '2511',
 '2514',
 '2515',
 '2516',
 '2520',
 '2524',
 '2527',
 '2528',
 '2530',
 '2534',
 '2535',
 '2536',
 '2537',
 '2538',
 '2539',
 '2540',
 '2542',
 '2543',
 '2545',
 '2546',
 '2547',
 '2548',
 '2597',
 '2601',
 '2603',
 '2605',
 '2606',
 '2607',
 '2608',
 '2609',
 '2610',
 '2611',
 '2612',
 '2613',
 '2614',
 '2615',
 '2616',
 '2617',
 '2618',
 '2701',
 '2702',
 '2704',
 '2705',
 '2706',
 '2707',
 '2801',
 '2809',
 '2812',
 '2816',
 '2820',
 '2823',
 '2832',
 '2833',
 '2834',
 '2836',
 '2837',
 '2838',
 '2841',
 '2845',
 '2847',
 '2849',
 '2850',
 '2851',
 '2852',
 '2854',
 '2855',
 '2856',
 '2880',
 '2881',
 '2882',
 '2883',
 '2884',
 '2885',
 '2886',
 '2887',
 '2887C',
 '2888',
 '2889',
 '2890',
 '2891',
 '2892',
 '2901',
 '2903',
 '2904',
 '2905',
 '2906',
 '2908',
 '2910',
 '2911',
 '2912',
 '2913',
 '2915',
 '3002',
 '3003',
 '3004',
 '3005',
 '3006',
 '3008',
 '3010',
 '3011',
 '3013',
 '3014',
 '3015',
 '3016',
 '3017',
 '3018',
 '3019',
 '3021',
 '3022',
 '3023',
 '3024',
 '3025',
 '3026',
 '3027',
 '3028',
 '3029',
 '3030',
 '3031',
 '3032',
 '3033',
 '3034',
 '3035',
 '3036',
 '3037',
 '3038',
 '3040',
 '3041',
 '3042',
 '3043',
 '3044',
 '3045',
 '3046',
 '3047',
 '3048',
 '3049',
 '3050',
 '3051',
 '3052',
 '3054',
 '3055',
 '3056',
 '3057',
 '3058',
 '3059',
 '3060',
 '3061',
 '3062',
 '3080',
 '3090',
 '3094',
 '3130',
 '3164',
 '3189',
 '3209',
 '3229',
 '3231',
 '3296',
 '3305',
 '3308',
 '3311',
 '3315',
 '3356',
 '3367',
 '3376',
 '3380',
 '3383',
 '3406',
 '3419',
 '3443',
 '3450',
 '3474',
 '3481',
 '3494',
 '3501',
 '3504',
 '3514',
 '3515',
 '3518',
 '3519',
 '3532',
 '3533',
 '3534',
 '3535',
 '3536',
 '3545',
 '3557',
 '3559',
 '3561',
 '3573',
 '3576',
 '3579',
 '3588',
 '3593',
 '3596',
 '3605',
 '3607',
 '3614',
 '3617',
 '3622',
 '3638',
 '3653',
 '3701',
 '3702',
 '3703',
 '4104',
 '4106',
 '4108',
 '4119',
 '4133',
 '4306',
 '4414',
 '4526',
 '4532',
 '4725',
 '4904',
 '4906',
 '5203',
 '5305',
 '5388',
 '5434',
 '5469',
 '5471',
 '5484',
 '5515',
 '5522',
 '5525',
 '5531',
 '5533',
 '5534',
 '5607',
 '5608',
 '5854',
 '6005',
 '6012',
 '6108',
 '6112',
 '6115',
 '6116',
 '6117',
 '6119',
 '6120',
 '6128',
 '6131',
 '6133',
 '6136',
 '6139',
 '6141',
 '6142',
 '6145',
 '6152',
 '6153',
 '6155',
 '6164',
 '6165',
 '6166',
 '6168',
 '6172',
 '6176',
 '6184',
 '6189',
 '6191',
 '6192',
 '6196',
 '6197',
 '6201',
 '6202',
 '6205',
 '6206',
 '6209',
 '6213',
 '6215',
 '6216',
 '6224',
 '6225',
 '6226',
 '6235',
 '6239',
 '6243',
 '6251',
 '6255',
 '6257',
 '6269',
 '6271',
 '6277',
 '6281',
 '6282',
 '6283',
 '6285',
 '6286',
 '6289',
 '6505',
 '6605',
 '8008',
 '8016',
 '8021',
 '8033',
 '8039',
 '8046',
 '8070',
 '8072',
 '8078',
 '8081',
 '8101',
 '8103',
 '8105',
 '8110',
 '8112',
 '8131',
 '8163',
 '8201',
 '8213',
 '8249',
 '8261',
 '8374',
 '8926',
 '8940',
 '9102',
 '9103',
 '910322',
 '9104',
 '910482',
 '9105',
 '910579',
 '9106',
 '9110',
 '911201',
 '911602',
 '911868',
 '912398',
 '9136',
 '913889',
 '9151',
 '9157',
 '9188',
 '9902',
 '9904',
 '9905',
 '9906',
 '9907',
 '9908',
 '9910',
 '9911',
 '9912',
 '9914',
 '9917',
 '9918',
 '9919',
 '9921',
 '9922',
 '9924',
 '9925',
 '9926',
 '9927',
 '9928',
 '9929',
 '9930',
 '9931',
 '9933',
 '9934',
 '9935',
 '9937',
 '9938',
 '9939',
 '9940',
 '9941',
 '9942',
 '9943',
 '9944',
 '9945',
 '9955',
 '9958',
 '4205',
 '4207',
 '4303',
 '4304',
 '4305',
 '6508',
 '8354',
 '9950',
 '4401',
 '4402',
 '4406',
 '4408',
 '4413',
 '4417',
 '4419',
 '4420',
 '4426',
 '1558',
 '1570',
 '1580',
 '2231',
 '3162',
 '4502',
 '4503',
 '4506',
 '4510',
 '4513',
 '4523',
 '4527',
 '4528',
 '4529',
 '4530',
 '4533',
 '4534',
 '4535',
 '6122',
 '6603',
 '6609',
 '8083',
 '8255',
 '8996',
 '9951',
 '4609',
 '2035',
 '5007',
 '5009',
 '5011',
 '5013',
 '5014',
 '5015',
 '5016',
 '8349',
 '8930',
 '9962',
 '2114',
 '5102',
 '2596',
 '4416',
 '5213',
 '5505',
 '5506',
 '5508',
 '5511',
 '5512',
 '5514',
 '5516',
 '5519',
 '5520',
 '5521',
 '5523',
 '5529',
 '5530',
 '6177',
 '2636',
 '5601',
 '5603',
 '5604',
 '5609',
 '5701',
 '5703',
 '5704',
 '5706',
 '5820',
 '6008',
 '6015',
 '6016',
 '6020',
 '6021',
 '6022',
 '6023',
 '6024',
 '2916',
 '5902',
 '5903',
 '5904',
 '5905',
 '8941',
 '9960',
 '1584',
 '2221',
 '3284',
 '3388',
 '5312',
 '8390',
 '8401',
 '8705',
 '8905',
 '8906',
 '8913',
 '8916',
 '8921',
 '8923',
 '8924',
 '8925',
 '8928',
 '8929',
 '8932',
 '8933',
 '8934',
 '8935',
 '8936',
 '8937',
 '8938',
 '8942',
 '9946',
 '9949',
 '1742',
 '1787',
 '4702',
 '4703',
 '4706',
 '4707',
 '4711',
 '4712',
 '4714',
 '4716',
 '4720',
 '4721',
 '4722',
 '4733',
 '6509',
 '1565',
 '1752',
 '1777',
 '1781',
 '1784',
 '1788',
 '1795',
 '1799',
 '1813',
 '3118',
 '3205',
 '3218',
 '3266',
 '4102',
 '4103',
 '4105',
 '4107',
 '4109',
 '4111',
 '4113',
 '4114',
 '4120',
 '4121',
 '4123',
 '4126',
 '4127',
 '4128',
 '4129',
 '4131',
 '8908',
 '8917',
 '8927',
 '8931',
 '3073',
 '3087',
 '3169',
 '3188',
 '3219',
 '3227',
 '3228',
 '3252',
 '3259',
 '3260',
 '3264',
 '3265',
 '3268',
 '3291',
 '3317',
 '3372',
 '3438',
 '3527',
 '3553',
 '3556',
 '5302',
 '5314',
 '5324',
 '5326',
 '5344',
 '5346',
 '5347',
 '5351',
 '5387',
 '5425',
 '5455',
 '5466',
 '5468',
 '5483',
 '5487',
 '6103',
 '6104',
 '6129',
 '6138',
 '6147',
 '6182',
 '6186',
 '6198',
 '6223',
 '6229',
 ...)

In [13]:
cursor.execute("select StockNo,StockName,ClosingPrice from stock")
data = cursor.fetchall()
df = pd.DataFrame(list(zip(*data.ado_results)))
df.shape
df

           0         1       2
0       0015        富邦    9.22
1       0050    元大台灣50  119.05
2       0051   元大中型100   27.00
3       0052      FB科技   44.00
4       0053      元大電子   31.12
...      ...       ...     ...
1923  00665L   FB H股正2   24.32
1924  00666R   FB H股反1   17.87
1925  00625K    FB上証+R    5.92
1926  00643K  群益深証中小+R    3.30
1927    3708      上緯投控  129.00

[1928 rows x 3 columns]

In [14]:
from PyStockBook.stock import Stock
v = Stock()
v.get_tpex_closing_price()
v.get_twse_closing_price()

In [15]:
v.twse.head()

   code      name   close
0  0050    元大台灣50  118.15
1  0051   元大中型100   57.35
2  0052      富邦科技  100.95
3  0053      元大電子   58.90
4  0055  元大MSCI金融   22.33

In [16]:
v.tpex.head()

     code      name  close
0  006201    元大富櫃50  17.89
1  00679B   元大美債20年  32.15
2  00687B   國泰20年美債  33.15
3  00694B   富邦美債1-3  38.60
4  00695B  富邦美債7-10  34.87

In [28]:
res = requests.get(url="https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_AVG_ALL")

In [29]:
res.json()[0]

{'Code': '0050',
 'Name': '元大台灣50',
 'ClosingPrice': '118.15',
 'MonthlyAveragePrice': '119.97'}

In [31]:
[r for r in res.json() if r['Code']=='1472']

[{'Code': '1472',
  'Name': '三洋實業',
  'ClosingPrice': '',
  'MonthlyAveragePrice': '28.71'}]

In [44]:
v.twse['code'] = v.twse['code'].astype('category')
v.twse['name'] = v.twse['name'].astype('category')
v.twse['close'] = pd.to_numeric(v.twse['close'], errors='coerce').fillna(0)
v.tpex['code'] = v.tpex['code'].astype('category')
v.tpex['name'] = v.tpex['name'].astype('category')
v.tpex['close'] = pd.to_numeric(v.twse['close'], errors='coerce').fillna(0)

In [45]:
v.twse.dtypes

code     category
name     category
close     float64
dtype: object